"""Brønnøysundregistrene's open Enhetsregisteret API: bulk download, single lookups, attribution.

Verified against the official documentation (https://data.brreg.no/enhetsregisteret/api/dokumentasjon/no/index.html)
and live responses on 2026-10-01:

- Bulk files: ``/api/enheter/lastned/csv`` (~155 MB gzip) and ``/api/underenheter/lastned/csv`` (gzip CSV).
  Produced every night around 05:00; ``etag`` and ``last-modified`` tell whether a file has changed. Cells are all
  quoted and may contain line breaks and doubled quotes.
- Search (``/api/enheter``) is capped at 10 000 results per query, so the bulk files are the supported way to get
  the whole register. Single lookups: ``/api/enheter/{orgnr}`` and ``/api/underenheter/{orgnr}``; an unknown
  number returns 404.
- Copies must drop units that are removed from open data ("Fjernet"); a full bulk reload does that.
- ``antallAnsatte`` is null for 0-4 employees; ``harRegistrertAntallAnsatte`` tells 0 from 1-4.
- No rate limit is published in the documentation (TODO(verify) with opendata@brreg.no). Prospect Signal makes
  requests only when the user asks, one at a time.
- Licence: Norsk lisens for offentlige data (NLOD) 2.0. Attribution wording follows NLOD § 5.
"""

from __future__ import annotations

from dataclasses import dataclass
from datetime import date
from pathlib import Path
from typing import Callable

import requests

from . import orgnr as orgnr_rules
from .errors import DataProblem, RegisterUnavailable
from .http import make_session
from .regions import fylke_for_kommune
from .schema import PERSON_NAME_FORMS, UNIT_COLUMNS, UNKNOWN_FORM, band_for

API_ROOT = "https://data.brreg.no/enhetsregisteret/api"
BULK_URLS = {
    "enheter": f"{API_ROOT}/enheter/lastned/csv",
    "underenheter": f"{API_ROOT}/underenheter/lastned/csv",
}
REGISTER_PAGE = "https://virksomhet.brreg.no/nb/oppslag/{kind}/{orgnr}"
DOCS_URL = "https://data.brreg.no/enhetsregisteret/api/dokumentasjon/no/index.html"
LICENCE_URL = "https://data.norge.no/nlod/en/2.0"
LICENCE_NAME = "Norwegian Licence for Open Government Data (NLOD) 2.0"

ATTRIBUTION = (
# NLOD § 5 default wording from the licence's official English version (data.norge.no/nlod/en/2.0), plus the
# required note that the data were changed.
    "Contains data under the Norwegian licence for Open Government data (NLOD) distributed by "
    "Brønnøysundregistrene. Prospect Signal filtered the data and derived employee bands and counties."
)
DEMO_ATTRIBUTION = "Fictional DEMO data generated by Prospect Signal. Not from Brønnøysundregistrene."
ATTRIBUTION_EN = ATTRIBUTION  # kept for the public API; the app writes English only
CONSENT_NOTE = (
    "Registry data never implies marketing consent. A company being listed in Enhetsregisteret does not mean it, "
    "or anyone working there, has agreed to receive marketing."
)

CHUNK_BYTES = 1024 * 1024
TIMEOUT = (15, 120)


@dataclass(frozen=True)
class BulkFile:
    kind: str
    path: Path
    bytes: int
    etag: str
    last_modified: str


ProgressCallback = Callable[[str, int, int | None], None]


def register_url(org_nr: str, entity_kind: str = "hovedenhet") -> str:
    kind = "underenheter" if entity_kind == "underenhet" else "enheter"
    return REGISTER_PAGE.format(kind=kind, orgnr=org_nr)


def bulk_headers(kind: str, session: requests.Session | None = None) -> dict[str, str]:
    """HEAD request: size, etag and last-modified of today's bulk file, without downloading it."""
    session = session or make_session()
    try:
        response = session.head(BULK_URLS[kind], timeout=TIMEOUT, allow_redirects=True)
        response.raise_for_status()
    except requests.RequestException as exc:
        raise RegisterUnavailable(f"Could not reach Brønnøysundregistrene ({kind}): {exc}") from exc
    return {key.lower(): value for key, value in response.headers.items()}


def download_bulk(
    kind: str,
    destination: Path,
    *,
    progress: ProgressCallback | None = None,
    session: requests.Session | None = None,
) -> BulkFile:
    """Stream one bulk CSV (gzip) to disk. Writes to ``*.part`` first so an interrupted download never looks done."""
    if kind not in BULK_URLS:
        raise DataProblem(f"Unknown bulk file: {kind}")
    session = session or make_session()
    destination = Path(destination)
    destination.parent.mkdir(parents=True, exist_ok=True)
    partial = destination.with_suffix(destination.suffix + ".part")
    try:
        with session.get(BULK_URLS[kind], stream=True, timeout=TIMEOUT) as response:
            response.raise_for_status()
            total = int(response.headers.get("content-length") or 0) or None
            done = 0
            with partial.open("wb") as handle:
                for chunk in response.iter_content(chunk_size=CHUNK_BYTES):
                    if not chunk:
                        continue
                    handle.write(chunk)
                    done += len(chunk)
                    if progress:
                        progress(kind, done, total)
            headers = {key.lower(): value for key, value in response.headers.items()}
    except requests.RequestException as exc:
        partial.unlink(missing_ok=True)
        raise RegisterUnavailable(f"The {kind} download from Brønnøysundregistrene failed: {exc}") from exc
    if total is not None and done != total:
        partial.unlink(missing_ok=True)
        raise RegisterUnavailable(f"The {kind} download was incomplete ({done:,} of {total:,} bytes).")
    partial.replace(destination)
    return BulkFile(kind, destination, done, headers.get("etag", ""), headers.get("last-modified", ""))


def load_register(
    store,
    data_dir: Path,
    *,
    include_underenheter: bool = False,
    progress: ProgressCallback | None = None,
    on_indexing: Callable[[str], None] | None = None,
    keep_files: bool = False,
    session: requests.Session | None = None,
    today: date | None = None,
) -> dict[str, object]:
    """Download the bulk file(s) and index them into ``store``. Returns a summary for display."""
    session = session or make_session()
    raw_dir = Path(data_dir) / "raw"
    files = {"enheter": download_bulk("enheter", raw_dir / "enheter.csv.gz", progress=progress, session=session)}
    if include_underenheter:
        files["underenheter"] = download_bulk(
            "underenheter", raw_dir / "underenheter.csv.gz", progress=progress, session=session
        )
    if on_indexing:
        on_indexing("Indexing the register locally (about 10–30 seconds)…")
    downloaded = today or date.today()
    counts = store.import_bulk(
        files["enheter"].path,
        files["underenheter"].path if "underenheter" in files else None,
        downloaded_at=downloaded,
        published={kind: bulk.last_modified for kind, bulk in files.items()},
    )
    store.set_meta("dataset", "register")
    store.set_meta("downloaded_at", downloaded.isoformat())
    for kind, bulk in files.items():
        store.set_meta(f"{kind}_last_modified", bulk.last_modified)
        store.set_meta(f"{kind}_etag", bulk.etag)
        store.set_meta(f"{kind}_bytes", bulk.bytes)
    store.set_meta("includes_underenheter", "yes" if include_underenheter else "no")
    store.set_meta("attribution", ATTRIBUTION)
    if not keep_files:
        for bulk in files.values():
            bulk.path.unlink(missing_ok=True)
    return {"counts": counts, "downloaded_at": downloaded.isoformat(), "files": files}


# -- single lookups ---------------------------------------------------------------------------------------------
def _lines(address: dict | None) -> str:
    if not address:
        return ""
    return ", ".join(line.strip() for line in address.get("adresse") or [] if line and line.strip())


def _code(block: dict | None) -> tuple[str | None, str | None]:
    if not block:
        return None, None
    return block.get("kode") or None, block.get("beskrivelse") or None


def _date(value: str | None) -> date | None:
    if not value:
        return None
    try:
        return date.fromisoformat(value[:10])
    except ValueError:
        return None


def normalise_api_unit(
    payload: dict,
    entity_kind: str,
    *,
    parent: dict | None = None,
    downloaded_at: date | None = None,
) -> dict:
    """Map one API JSON object onto the stored schema. Person and contact fields are never copied.

    For an underenhet, pass the parent's stored row (``parent``) so the legal form and status flags are inherited,
    exactly as in the bulk import.
    """
    org_nr = str(payload.get("organisasjonsnummer") or "")
    if len(org_nr) != 9 or not org_nr.isdigit():
        raise DataProblem(f"Unexpected organisation number in API response: {org_nr!r}")
    is_sub = entity_kind == "underenhet"
    nace = [_code(payload.get(f"naeringskode{i}")) for i in (1, 2, 3)]
    location = payload.get("beliggenhetsadresse" if is_sub else "forretningsadresse") or {}
    if not (location.get("kommunenummer") or location.get("postnummer")):
        location = payload.get("postadresse") or {}
    own_form, own_form_desc = _code(payload.get("organisasjonsform"))
    if is_sub:
        org_form = (parent or {}).get("org_form") or UNKNOWN_FORM
        org_form_desc = (parent or {}).get("org_form_desc") or "Parent not in the local register"
    else:
        org_form, org_form_desc = own_form, own_form_desc
    employees = payload.get("antallAnsatte")
    has_employees = bool(payload.get("harRegistrertAntallAnsatte"))
    kommune_nr = location.get("kommunenummer") or None
    country = location.get("landkode") or None
    activity = payload.get("aktivitet")
    record = {
        "org_nr": org_nr,
        "name": payload.get("navn"),
        "entity_kind": entity_kind,
        "parent_org_nr": payload.get("overordnetEnhet") or None,
        "org_form": org_form,
        "org_form_desc": org_form_desc,
        "unit_form": own_form,
        "nace1": nace[0][0],
        "nace1_desc": nace[0][1],
        "nace2": nace[1][0],
        "nace2_desc": nace[1][1],
        "nace3": nace[2][0],
        "nace3_desc": nace[2][1],
        "has_employees": has_employees,
        "employees": int(employees) if employees is not None else None,
        "employee_band": band_for(employees, has_employees),
        "founded": _date(payload.get("oppstartsdato" if is_sub else "stiftelsesdato")),
        "registered": _date(payload.get("registreringsdatoEnhetsregisteret")),
        "vat_registered": bool(payload.get("registrertIMvaregisteret")),
        "in_business_register": bool(
            (parent or {}).get("in_business_register") if is_sub else payload.get("registrertIForetaksregisteret")
        ),
        "bankrupt": bool((parent or {}).get("bankrupt") if is_sub else payload.get("konkurs")),
        "winding_up": bool((parent or {}).get("winding_up") if is_sub else payload.get("underAvvikling")),
        "forced_winding_up": bool(
            (parent or {}).get("forced_winding_up")
            if is_sub
            else payload.get("underTvangsavviklingEllerTvangsopplosning")
        ),
        "closed": bool(payload.get("nedleggelsesdato")) if is_sub else False,
        "address": "" if org_form in PERSON_NAME_FORMS else _lines(location),
        "postcode": location.get("postnummer") or None,
        "poststed": location.get("poststed") or None,
        "kommune_nr": kommune_nr,
        "kommune": location.get("kommune") or None,
        "fylke_nr": fylke_for_kommune(kommune_nr) if (country or "NO") == "NO" else None,
        "country_code": country,
        "website": payload.get("hjemmeside") or None,
        "activity": " ".join(activity) if isinstance(activity, list) else activity,
        "sector_code": _code(payload.get("institusjonellSektorkode"))[0],
        "is_demo": False,
        "source": "brreg-api",
        "downloaded_at": downloaded_at or date.today(),
        "source_published_at": "",
    }
    assert set(record) == set(UNIT_COLUMNS)
    return record


def fetch_unit(org_nr: str, session: requests.Session | None = None) -> tuple[str, dict] | None:
    """Look up one unit. Returns (entity_kind, JSON) or None when the number is not in open data.

    Tries hovedenhet first, then underenhet. TODO(verify): the documentation does not state the status code for
    units deleted or removed from open data; 404 and 410 are both treated as "not in open data".
    """
    org_nr = orgnr_rules.validate(org_nr)
    session = session or make_session()
    for kind, path in (("hovedenhet", "enheter"), ("underenhet", "underenheter")):
        try:
            response = session.get(
                f"{API_ROOT}/{path}/{org_nr}", timeout=TIMEOUT, headers={"Accept": "application/json"}
            )
        except requests.RequestException as exc:
            raise RegisterUnavailable(f"Could not reach Brønnøysundregistrene: {exc}") from exc
        if response.status_code in (404, 410):
            continue
        if response.status_code != 200:
            raise RegisterUnavailable(f"Brønnøysundregistrene answered {response.status_code} for {org_nr}.")
        payload = response.json()
        if payload.get("slettedato"):
            return None
        return kind, payload
    return None


def refresh_unit(store, org_nr: str, session: requests.Session | None = None) -> dict | None:
    """Re-fetch one unit and update the local copy. Removes it locally when it is no longer in open data."""
    found = fetch_unit(org_nr, session=session)
    org_nr = orgnr_rules.normalise(org_nr)
    if found is None:
        store.remove_unit(org_nr)
        return None
    kind, payload = found
    parent = None
    if kind == "underenhet" and payload.get("overordnetEnhet"):
        parent = store.get_unit(payload["overordnetEnhet"])
        if parent is None:
            parent_found = fetch_unit(payload["overordnetEnhet"], session=session)
            if parent_found:
                parent = normalise_api_unit(parent_found[1], parent_found[0])
    record = normalise_api_unit(payload, kind, parent=parent)
    store.upsert_unit(record)
    return record
