"""Offline demo: ~2,000 fictional companies so the app runs without network.

Everything here is generated by code. Names end in "(DEMO)", organisation numbers start with 0 and fail the MOD11
check on purpose (so they can never collide with, or be imported as, a real unit; Freddo rejects them), websites use
the reserved ``.example`` domain, and street addresses are fictional. Kommune numbers and names are real so the
region filters and map behave as they do on the real register.
"""

from __future__ import annotations

from datetime import date, timedelta
import random

import pandas as pd

from . import nace
from .orgnr import check_digit
from .regions import fylke_for_kommune
from .schema import UNIT_COLUMNS, band_for

DEMO_DATE = date(2026, 10, 1)
DEMO_SIZE = 2000
DEMO_SEED = 7

# (kommune_nr, kommune, base postcode, weight). Numbers and names as in Enhetsregisteret on 2026-10-01.
KOMMUNER: tuple[tuple[str, str, int, int], ...] = (
    ("0301", "OSLO", 150, 150),
    ("3201", "BÆRUM", 1338, 40),
    ("3203", "ASKER", 1384, 30),
    ("3205", "LILLESTRØM", 2000, 30),
    ("3207", "NORDRE FOLLO", 1400, 15),
    ("3209", "ULLENSAKER", 2050, 10),
    ("3101", "HALDEN", 1767, 15),
    ("3103", "MOSS", 1530, 20),
    ("3105", "SARPSBORG", 1710, 22),
    ("3107", "FREDRIKSTAD", 1606, 30),
    ("3110", "HVALER", 1680, 4),
    ("3112", "RÅDE", 1640, 5),
    ("3301", "DRAMMEN", 3015, 35),
    ("3303", "KONGSBERG", 3611, 12),
    ("3312", "LIER", 3400, 10),
    ("3314", "ØVRE EIKER", 3300, 6),
    ("3403", "HAMAR", 2317, 15),
    ("3405", "LILLEHAMMER", 2609, 15),
    ("3905", "TØNSBERG", 3110, 18),
    ("3907", "SANDEFJORD", 3210, 18),
    ("4003", "SKIEN", 3700, 15),
    ("4203", "ARENDAL", 4836, 12),
    ("4204", "KRISTIANSAND", 4610, 30),
    ("4601", "BERGEN", 5003, 70),
    ("1103", "STAVANGER", 4006, 40),
    ("1108", "SANDNES", 4307, 20),
    ("5001", "TRONDHEIM", 7010, 50),
    ("1506", "MOLDE", 6413, 10),
    ("1508", "ÅLESUND", 6002, 15),
    ("1804", "BODØ", 8006, 15),
    ("5501", "TROMSØ", 9008, 15),
    ("5601", "ALTA", 9510, 6),
)

# (code, weight). Food and beverage codes are over-represented so the demo ICP has something to find.
NACE_MIX: tuple[tuple[str, int], ...] = (
    ("10.110", 6),
    ("10.130", 8),
    ("10.203", 6),
    ("10.390", 6),
    ("10.510", 6),
    ("10.710", 30),
    ("10.720", 5),
    ("10.820", 8),
    ("10.830", 10),
    ("10.850", 8),
    ("10.890", 8),
    ("11.010", 5),
    ("11.030", 5),
    ("11.050", 16),
    ("11.070", 10),
    ("46.390", 25),
    ("47.110", 40),
    ("56.110", 60),
    ("43.210", 70),
    ("41.000", 50),
    ("62.100", 70),
    ("70.200", 60),
    ("68.200", 90),
    ("49.410", 40),
    ("86.210", 25),
    ("96.210", 30),
    ("00.000", 20),
)

ORG_FORM_MIX: tuple[tuple[str, int], ...] = (
    ("AS", 55),
    ("ENK", 27),
    ("ANS", 2),
    ("DA", 2),
    ("SA", 2),
    ("NUF", 3),
    ("FLI", 5),
    ("ASA", 1),
    ("STI", 3),
)
ORG_FORM_DESC = {
    "AS": "Aksjeselskap",
    "ENK": "Enkeltpersonforetak",
    "ANS": "Ansvarlig selskap",
    "DA": "Selskap med delt ansvar",
    "SA": "Samvirkeforetak",
    "NUF": "Norskregistrert utenlandsk foretak",
    "FLI": "Forening/lag/innretning",
    "ASA": "Allmennaksjeselskap",
    "STI": "Stiftelse",
}

PLACE_WORDS = (
    "Ørnes",
    "Åsen",
    "Bæklia",
    "Fjordlys",
    "Nordbris",
    "Lysthus",
    "Sølvberg",
    "Granholt",
    "Måkeskjær",
    "Tindved",
    "Elvebredd",
    "Furulund",
    "Kvitsand",
    "Røsslyng",
    "Havgløtt",
    "Steinrøys",
    "Bjørkely",
    "Myrull",
    "Skjærgård",
    "Vårsol",
    "Fjellro",
    "Lindehaug",
    "Østerli",
    "Vestvind",
    "Sjøbris",
    "Kløverstien",
    "Tyttebær",
    "Islandsmose",
)
TRADE_WORDS = {
    "10.1": ("Pølsemaker", "Kjøttvarer", "Spekemat"),
    "10.2": ("Sjømat", "Røkeri", "Fiskeforedling"),
    "10.3": ("Saftpresseri", "Grønt"),
    "10.5": ("Meieri", "Ysteri"),
    "10.7": ("Bakeri", "Konditori", "Bakerhus"),
    "10.82": ("Sjokolade", "Konfekt"),
    "10.83": ("Kafferisteri", "Tehus"),
    "10": ("Matverksted", "Matmanufaktur"),
    "11": ("Bryggeri", "Siderhus", "Destilleri", "Mineralvann", "Drikkeverk"),
    "46": ("Engros", "Matgrossist"),
    "47": ("Nærbutikk", "Landhandel"),
    "56": ("Kro", "Restaurant", "Spiseri"),
    "43": ("Elektro", "Installasjon"),
    "41": ("Bygg", "Byggmester"),
    "62": ("Data", "Programvare", "Digital"),
    "70": ("Rådgivning", "Konsult"),
    "68": ("Eiendom", "Gårdeier"),
    "49": ("Transport", "Frakt"),
    "86": ("Legesenter", "Helsehus"),
    "96": ("Frisør", "Salong"),
    "00": ("Holding", "Invest"),
}
FIRST_NAMES = ("Kari", "Ola", "Åse", "Øystein", "Ingrid", "Bjørn", "Sigrid", "Håkon", "Liv", "Ærlend")
FICTIONAL_SURNAMES = ("Demosen", "Prøvesen", "Eksempelsen", "Fiktivsen", "Testrud", "Øvingstad")
STREETS = ("Demoveien", "Prøvegata", "Eksempelstien", "Fiktivbakken", "Testvegen", "Øvingsallé")


def fake_orgnr(index: int) -> str:
    """A nine-character number starting with 0 whose last digit deliberately breaks MOD11."""
    base = f"0{index:07d}"
    expected = check_digit(base)
    wrong = 0 if expected is None else (expected + 1) % 10
    return base + str(wrong)


def _weighted(rng: random.Random, options: tuple[tuple, ...]):
    return rng.choices(options, weights=[option[-1] for option in options], k=1)[0]


def _employees(rng: random.Random, org_form: str, is_food: bool) -> int:
    if org_form == "ENK":
        return rng.choices([0, 1, 2, 3, 5, 7], weights=[70, 12, 8, 4, 4, 2])[0]
    if org_form in ("FLI", "STI"):
        return rng.choices([0, 2, 6, 15], weights=[60, 20, 15, 5])[0]
    roll = rng.random()
    if roll < (0.15 if is_food else 0.35):
        return 0
    if roll < (0.30 if is_food else 0.55):
        return rng.randint(1, 4)
    # Long-tailed sizes; food producers skew larger in the demo.
    size = int(rng.lognormvariate(2.9 if is_food else 2.4, 0.9))
    return max(5, min(size, 1800))


def _random_date(rng: random.Random, start: date, end: date) -> date:
    return start + timedelta(days=rng.randint(0, (end - start).days))


def make_demo_units(size: int = DEMO_SIZE, seed: int = DEMO_SEED) -> pd.DataFrame:
    """Deterministic fictional units in the stored schema (hovedenheter plus some underenheter)."""
    rng = random.Random(seed)
    indexes = rng.sample(range(1_000_000, 9_999_999), size + size // 10)
    rows: list[dict] = []
    used_names: set[str] = set()
    for number in range(size):
        org_form = _weighted(rng, ORG_FORM_MIX)[0]
        code = _weighted(rng, NACE_MIX)[0]
        division = code[:2]
        is_food = division in ("10", "11")
        kommune_nr, kommune, base_postcode, _ = _weighted(rng, KOMMUNER)
        trade_key = max((key for key in TRADE_WORDS if code.startswith(key)), key=len)
        trade = rng.choice(TRADE_WORDS[trade_key])
        if org_form == "ENK":
            stem = f"{rng.choice(FIRST_NAMES)} {rng.choice(FICTIONAL_SURNAMES)} {trade}"
            name = stem
        else:
            stem = f"{rng.choice(PLACE_WORDS)} {trade}"
            name = f"{stem} {org_form}"
        attempt = 1
        while name in used_names:
            attempt += 1
            name = f"{stem} {attempt}" if org_form == "ENK" else f"{stem} {attempt} {org_form}"
        used_names.add(name)
        employees = _employees(rng, org_form, is_food)
        has_employees = employees > 0
        stored_employees = employees if employees >= 5 else None  # the register hides 1-4
        founded = _random_date(rng, date(1965, 1, 1), date(2026, 6, 30))
        registered = founded if founded >= date(1995, 2, 1) else _random_date(rng, date(1995, 2, 1), date(1996, 12, 31))
        status_roll = rng.random()
        slug = name.lower().replace(" ", "-")
        rows.append(
            {
                "org_nr": fake_orgnr(indexes[number]),
                "name": f"{name} (DEMO)",
                "entity_kind": "hovedenhet",
                "parent_org_nr": None,
                "org_form": org_form,
                "org_form_desc": ORG_FORM_DESC[org_form],
                "unit_form": org_form,
                "nace1": code,
                "nace1_desc": nace.name(code),
                "nace2": None,
                "nace2_desc": None,
                "nace3": None,
                "nace3_desc": None,
                "has_employees": has_employees,
                "employees": stored_employees,
                "employee_band": band_for(stored_employees, has_employees),
                "founded": founded,
                "registered": registered,
                "vat_registered": rng.random() < (0.85 if has_employees else 0.35),
                "in_business_register": org_form in ("AS", "ASA", "ANS", "DA", "SA", "NUF") or rng.random() < 0.3,
                "bankrupt": status_roll < 0.02,
                "winding_up": 0.02 <= status_roll < 0.04,
                "forced_winding_up": 0.04 <= status_roll < 0.045,
                "closed": False,
                "address": "" if org_form == "ENK" else f"{rng.choice(STREETS)} {rng.randint(1, 120)}",
                "postcode": f"{(base_postcode + rng.randint(0, 40)) % 10000:04d}",
                "poststed": kommune,
                "kommune_nr": kommune_nr,
                "kommune": kommune,
                "fylke_nr": fylke_for_kommune(kommune_nr),
                "country_code": "NO",
                "website": f"www.{slug}.example" if org_form != "ENK" and rng.random() < 0.45 else None,
                "activity": "Fiktiv virksomhet laget for demonstrasjon av ProspectSignal.",
                "sector_code": None,
                "is_demo": True,
                "source": "demo",
                "downloaded_at": DEMO_DATE,
                "source_published_at": "",
            }
        )
    # A few sub-units (locations) under larger fictional companies, sometimes in another county.
    parents = [row for row in rows if row["org_form"] in ("AS", "ASA") and (row["employees"] or 0) >= 20]
    for offset, parent in enumerate(parents[: size // 10]):
        kommune_nr, kommune, base_postcode, _ = _weighted(rng, KOMMUNER)
        employees = max(5, int((parent["employees"] or 5) * rng.uniform(0.2, 0.6)))
        rows.append(
            {
                **parent,
                "org_nr": fake_orgnr(indexes[size + offset]),
                "name": parent["name"].replace(" (DEMO)", f" avd. {kommune.title()} (DEMO)"),
                "entity_kind": "underenhet",
                "parent_org_nr": parent["org_nr"],
                "unit_form": "BEDR",
                "employees": employees,
                "has_employees": True,
                "employee_band": band_for(employees, True),
                "founded": _random_date(rng, parent["founded"], date(2026, 6, 30)),
                "address": f"{rng.choice(STREETS)} {rng.randint(1, 120)}",
                "postcode": f"{(base_postcode + rng.randint(0, 40)) % 10000:04d}",
                "poststed": kommune,
                "kommune_nr": kommune_nr,
                "kommune": kommune,
                "fylke_nr": fylke_for_kommune(kommune_nr),
                "website": None,
                "activity": None,
            }
        )
    frame = pd.DataFrame(rows, columns=list(UNIT_COLUMNS))
    return frame


def load_demo(store) -> int:
    """Fill ``store`` with the demo units and mark it as the demo dataset."""
    count = store.replace_units(make_demo_units())
    store.set_meta("dataset", "demo")
    store.set_meta("downloaded_at", DEMO_DATE.isoformat())
    store.set_meta("demo_version", f"{DEMO_SIZE}-{DEMO_SEED}")
    return count
